MVCForum.Website/ViewModels/PrivateMessageViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using MVCForum.Domain.DomainModel;
using MVCForum.Website.Application;

namespace MVCForum.Website.ViewModels
{
    public class ListPrivateMessageViewModel
    {
        public IList<PrivateMessage> Messages { get; set; }
        public int? PageIndex { get; set; }
        public int? TotalCount { get; set; }
    }

    public class CreatePrivateMessageViewModel
    {
        [ForumMvcResourceDisplayName("PM.RecipientUsername")]
        [StringLength(150)]
        [Required]
        public string UserToUsername { get; set; }

        [ForumMvcResourceDisplayName("PM.MessageSubject")]
        [Required]
        public string Subject { get; set; }

        //[UIHint("bbeditor"), AllowHtml]
        [UIHint("markdowneditor"), AllowHtml]
        public string Message { get; set; }

        public string PreviousMessage { get; set; }

    }

    public class ViewPrivateMessageViewModel
    {
        public PrivateMessage Message { get; set; }
    }

    public class DeletePrivateMessageViewModel
    {
        public Guid Id { get; set; }
    }


}

MVCForum.Website/Controllers/PrivateMessageController.cs
using System;
using System.Web.Mvc;
using MVCForum.Domain.Constants;
using MVCForum.Domain.DomainModel;
using MVCForum.Domain.Interfaces.Services;
using MVCForum.Domain.Interfaces.UnitOfWork;
using MVCForum.Utilities;
using MVCForum.Website.Areas.Admin.ViewModels;
using MVCForum.Website.ViewModels;

namespace MVCForum.Website.Controllers
{
    [Authorize]
    public class PrivateMessageController : BaseController
    {
        private readonly IPrivateMessageService _privateMessageService;

        public PrivateMessageController(ILoggingService loggingService, IUnitOfWorkManager unitOfWorkManager, IMembershipService membershipService,
            ILocalizationService localizationService, IRoleService roleService, ISettingsService settingsService, IPrivateMessageService privateMessageService)
            : base(loggingService, unitOfWorkManager, membershipService, localizationService, roleService, settingsService)
        {
            _privateMessageService = privateMessageService;
        }

        public ActionResult Index(int? p)
        {
            using (UnitOfWorkManager.NewUnitOfWork())
            {
                var pageIndex = p ?? 1;
                var pagedMessages = _privateMessageService.GetPagedReceivedMessagesByUser(pageIndex, AppConstants.PrivateMessageListSize, LoggedOnUser);
                var viewModel = new ListPrivateMessageViewModel
                {
                    Messages = pagedMessages,
                    PageIndex = pageIndex,
                    TotalCount = pagedMessages.TotalCount
                };
                return View(viewModel);
            }
        }

        public ActionResult SentMessages(int? p)
        {
            using (UnitOfWorkManager.NewUnitOfWork())
            {
                var pageIndex = p ?? 1;
                var pagedMessages = _privateMessageService.GetPagedSentMessagesByUser(pageIndex, AppConstants.PrivateMessageListSize, LoggedOnUser);
                var viewModel = new ListPrivateMessageViewModel
                {
                    Messages = pagedMessages
                };
                return View(viewModel);
            }
        }

        public ActionResult Create(Guid? id)
        {
            // Check if private messages are enabled
            if(!SettingsService.GetSettings().EnablePrivateMessages)
            {
                return ErrorToHomePage(LocalizationService.GetResourceString("Errors.GenericMessage"));
            }

            // Check flood control
            var lastMessage = _privateMessageService.GetLastSentPrivateMessage(LoggedOnUser.Id);
            if (lastMessage != null && DateUtils.TimeDifferenceInMinutes(DateTime.Now, lastMessage.DateSent) < SettingsService.GetSettings().PrivateMessageFloodControl)
            {
                return ErrorToInbox(LocalizationService.GetResourceString("PM.SendingToQuickly"));
            }

            // Check outbox size
            var senderCount = _privateMessageService.GetAllSentByUser(LoggedOnUser.Id).Count;
            if (senderCount > SettingsService.GetSettings().MaxPrivateMessagesPerMember)
            {
                return ErrorToInbox(LocalizationService.GetResourceString("PM.SentItemsOverCapcity"));
            }

            var viewModel = new CreatePrivateMessageViewModel();
            // See if this is a reply or not
            if (id != null)
            {
                var previousMessage = _privateMessageService.Get((Guid)id);
                // Its a reply, get the details
                viewModel.UserToUsername = previousMessage.UserFrom.UserName;
                viewModel.Subject = previousMessage.Subject;
                viewModel.PreviousMessage = previousMessage.Message;
            }
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreatePrivateMessageViewModel createPrivateMessageViewModel)
        {
            if (!SettingsService.GetSettings().EnablePrivateMessages)
            {
                return ErrorToHomePage(LocalizationService.GetResourceString("Errors.GenericMessage"));
            }
            using (var unitOfWork = UnitOfWorkManager.NewUnitOfWork())
            {
                if (ModelState.IsValid)
                {
                    var userTo = createPrivateMessageViewModel.UserToUsername;

                    // first check they are not trying to message themself!
                    if (userTo.ToLower() != LoggedOnUser.UserName.ToLower())
                    {
                        // Map the view model to message
                        var privateMessage = new PrivateMessage
                                                 {
                                                     UserFrom = LoggedOnUser,
                                                     Subject = createPrivateMessageViewModel.Subject,
                                                     Message = createPrivateMessageViewModel.Message,
                                                 };                            
                        // now get the user its being sent to
                        var memberTo = MembershipService.GetUser(userTo);

                        // check the member
                        if (memberTo != null)
                        {

                            // Check in box size
                            // First check sender
                            var receiverCount = _privateMessageService.GetAllReceivedByUser(memberTo.Id).Count;
                            if (receiverCount > SettingsService.GetSettings().MaxPrivateMessagesPerMember)
                            {
                                ModelState.AddModelError(string.Empty, string.Format(LocalizationService.GetResourceString("PM.ReceivedItemsOverCapcity"), memberTo.UserName));
                            }
                            else
                            {
                                // Good to go send the message!
                                privateMessage.UserTo = memberTo;
                                _privateMessageService.Add(privateMessage);

                                try
                                {
                                    TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                                    {
                                        Message = LocalizationService.GetResourceString("PM.MessageSent"),
                                        MessageType = GenericMessages.success
                                    };

                                    unitOfWork.Commit();

                                    return RedirectToAction("Index");
                                }
                                catch (Exception ex)
                                {
                                    unitOfWork.Rollback();
                                    LoggingService.Error(ex);
                                    ModelState.AddModelError(string.Empty, LocalizationService.GetResourceString("Errors.GenericMessage"));
                                }   
                            }
                        }
                        else
                        {
                            // Error send back to user
                            ModelState.AddModelError(string.Empty, LocalizationService.GetResourceString("PM.UnableFindMember"));
                        }
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, LocalizationService.GetResourceString("PM.TalkToSelf"));
                    }
                }
                TempData[AppConstants.MessageViewBagName] = null;
                return View(createPrivateMessageViewModel);
            }
        }

        public ActionResult View(Guid id)
        {
            using (var unitOfWork = UnitOfWorkManager.NewUnitOfWork())
            {
                var message = _privateMessageService.Get(id);

                if (message.UserTo == LoggedOnUser | message.UserFrom == LoggedOnUser)
                {
                    //Mark as read if this is the receiver of the message
                    if (message.UserTo == LoggedOnUser)
                    {
                        // Update message as read
                        message.IsRead = true;

                        try
                        {
                            unitOfWork.Commit();
                        }
                        catch (Exception ex)
                        {
                            unitOfWork.Rollback();
                            LoggingService.Error(ex);
                        }
                    }

                    return View(new ViewPrivateMessageViewModel { Message = message });
                }

                return ErrorToHomePage(LocalizationService.GetResourceString("Errors.NoPermission"));
            }
        }

        [HttpPost]
        public ActionResult Delete(DeletePrivateMessageViewModel deletePrivateMessageViewModel)
        {
            using (var unitOfWork = UnitOfWorkManager.NewUnitOfWork())
            {
                if (Request.IsAjaxRequest())
                {
                    var privateMessage = _privateMessageService.Get(deletePrivateMessageViewModel.Id);
                    if (privateMessage.UserTo == LoggedOnUser | privateMessage.UserFrom == LoggedOnUser)
                    {
                        _privateMessageService.DeleteMessage(privateMessage);
                    }
                    else
                    {
                        throw new Exception(LocalizationService.GetResourceString("Errors.NoPermission"));
                    }
                }

                try
                {
                    unitOfWork.Commit();
                }
                catch (Exception ex)
                {
                    unitOfWork.Rollback();

MVCForum.Website/Controllers/TagController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCForum.Domain.Constants;
using MVCForum.Domain.Interfaces.Services;
using MVCForum.Domain.Interfaces.UnitOfWork;
using MVCForum.Website.ViewModels;

namespace MVCForum.Website.Controllers
{
    public class TagController : BaseController
    {
        private readonly ITopicTagService _topicTagService;

        public TagController(ILoggingService loggingService, IUnitOfWorkManager unitOfWorkManager, IMembershipService membershipService, ILocalizationService localizationService, IRoleService roleService, ISettingsService settingsService, ITopicTagService topicTagService)
            : base(loggingService, unitOfWorkManager, membershipService, localizationService, roleService, settingsService)
        {
            _topicTagService = topicTagService;
        }

        [ChildActionOnly]
        [OutputCache(Duration = AppConstants.DefaultCacheLengthInSeconds)]
        public PartialViewResult PopularTags()
        {
            using (UnitOfWorkManager.NewUnitOfWork())
            {
                var popularTags = _topicTagService.GetPopularTags(20);
                var viewModel = new PopularTagViewModel { PopularTags = popularTags };
                return PartialView(viewModel);
            }
        }

    }
}

MVCForum.Website/Views/PrivateMessage/Create.cshtml
@using MVCForum.Utilities
@model MVCForum.Website.ViewModels.CreatePrivateMessageViewModel
@{
    ViewBag.Title = Html.LanguageString("PM.CreatePrivateMessage");
}
@section Header
{
    @(
        Bundle.JavaScript()
            .Add("~/Scripts/jquery.validate.min.js")
            .Add("~/Scripts/jquery.validate.unobtrusive.min.js")
            
            .MvcRender("~/scripts/cache/validate-combined_#.js")
    )
    <script src="@Url.Content("~/Scripts/jquery-ui-1.10.0.min.js")" type="text/javascript"></script>
    <script type="text/javascript">
        $(function () {
            $("input#UserToUsername").autocomplete({
                source: app_base + "Members/Autocomplete"
            });
        });
    </script>
}
@section side
{
    @Html.Action("ListCategorySideMenu", "Category")
    @Html.Action("PopularTags", "Tag")
}
@using (Html.BeginForm("Create", "PrivateMessage", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.ValidationSummary(true)
    @Html.AntiForgeryToken()

    <fieldset>
        <legend>@ViewBag.Title</legend>
        <div class="editor-label">
            @Html.LabelFor(model => model.UserToUsername)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UserToUsername, new { @class = "usertotextbox"})
            @Html.ValidationMessageFor(model => model.UserToUsername)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Subject)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Subject)
            @Html.ValidationMessageFor(model => model.Subject)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Message)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Message)
            @Html.ValidationMessageFor(model => model.Message)
        </div>
        <div class="submit-holder">
            <input type="submit" class="btn btn-large btn-success" value="@Html.LanguageString("PM.Send")" />
        </div>
    </fieldset>
}

@if (!string.IsNullOrEmpty(Model.PreviousMessage))
{
    <p class="previousmessageholder">
        <span class="originalmessage">@Html.LanguageString("PM.OriginalMessage")</span>
        @Html.Raw(AppHelpers.ConvertPostContent(Model.PreviousMessage))
    </p>
}

MVCForum.Website/Views/PrivateMessage/Index.cshtml
@model MVCForum.Website.ViewModels.ListPrivateMessageViewModel

@{
    ViewBag.Title = Html.LanguageString("PM.ReceivedPrivateMessages");
}

<h2>@ViewBag.Title</h2>

@if(Model.Messages.Any())
{
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>@Html.LanguageString("PM.From")</th>
            <th>@Html.LanguageString("PM.Subject")</th>
            <th>@Html.LanguageString("PM.Date")</th>
            <th>@Html.LanguageString("PM.Read")</th>
            <th>@Html.LanguageString("PM.Delete")</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var message in Model.Messages)
        {        
            <tr>
                <td>
                    <strong><a href="@Html.Raw(message.UserFrom.NiceUrl)">@Html.Raw(message.UserFrom.UserName)</a></strong>
                </td>
                <td>
                    @Html.ActionLink(message.Subject, "View", new { id = message.Id})
                </td>
                <td>@message.DateSent.ToShortDateString()</td>
                <td>@Html.DisplayFor(modelItem => message.IsRead)</td>
                <td>
                    <a class="privatemessagedelete" rel="@message.Id">
                      <i class="icon-remove"></i>  
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

@Html.Pager(Convert.ToInt32(Model.PageIndex), MVCForum.Domain.Constants.AppConstants.PrivateMessageListSize, Convert.ToInt32(Model.TotalCount), new {})    
}
else
{
    <p>@Html.LanguageString("PM.NoMessages")</p>
}


<div class="btn-group">    
        @Html.ActionLink(Html.LanguageString("PM.SentPrivateMessages"), "SentMessages", new { }, new { @class = "btn btn-success" })
        @Html.ActionLink(Html.LanguageString("PM.Create"), "Create", "PrivateMessage", new { }, new { @class = "btn btn-success" })
</div>

MVCForum.Website/Views/PrivateMessage/SentMessages.cshtml
@model MVCForum.Website.ViewModels.ListPrivateMessageViewModel

@{
    ViewBag.Title = Html.LanguageString("PM.SentPrivateMessages");
}

<h2>@ViewBag.Title</h2>

@if(Model.Messages.Any())
{
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>@Html.LanguageString("PM.To")</th>
            <th>@Html.LanguageString("PM.Subject")</th>
            <th>@Html.LanguageString("PM.Date")</th>
            <th>@Html.LanguageString("PM.Read")</th>
            <th>@Html.LanguageString("PM.Delete")</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var message in Model.Messages)
        {        
            <tr>
                <td>
                    <strong><a href="@Html.Raw(message.UserTo.NiceUrl)">@Html.Raw(message.UserTo.UserName)</a></strong>
                </td>
                <td>
                    @Html.ActionLink(message.Subject, "View", new { id = message.Id})
                </td>
                <td>@message.DateSent.ToShortDateString()</td>
                <td>@Html.DisplayFor(modelItem => message.IsRead)</td>
                <td>
                    <a class="privatemessagedelete" rel="@message.Id">
                      <i class="icon-remove"></i>  
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>


@Html.Pager(Convert.ToInt32(Model.PageIndex), MVCForum.Domain.Constants.AppConstants.PrivateMessageListSize, Convert.ToInt32(Model.TotalCount), new {})    
}
else
{
    <p>@Html.LanguageString("PM.NoMessages")</p>
}


<div class="btn-group">    
        @Html.ActionLink(Html.LanguageString("PM.BackToInbox"), "Index", new { }, new { @class = "btn btn-success" })
        @Html.ActionLink(Html.LanguageString("PM.Create"), "Create", "PrivateMessage", new { }, new { @class = "btn btn-success" })
</div>

MVCForum.Website/Views/PrivateMessage/View.cshtml
@using MVCForum.Utilities
@model MVCForum.Website.ViewModels.ViewPrivateMessageViewModel

@{
    ViewBag.Title = string.Concat(Html.LanguageString("PM.Title"), Model.Message.Subject);
}

<h2>@Model.Message.Subject</h2>
<p class="privatemessagefrom"><strong>@Html.LanguageString("PM.From")</strong> <a href="@Model.Message.UserFrom.NiceUrl">@Model.Message.UserFrom.UserName</a></p>
<p class="privatemessagesent"><strong>@Html.LanguageString("PM.Sent")</strong> @Model.Message.DateSent.ToShortDateString()</p>

<p class="privatemessagecontent">
    @Html.Raw(AppHelpers.ConvertPostContent(Model.Message.Message))
</p>

<div class="btn-group">    
        @Html.ActionLink(Html.LanguageString("PM.BackToInbox"), "Index", new { }, new { @class = "btn btn-success" })
        @Html.ActionLink(Html.LanguageString("PM.Reply"), "Create", "PrivateMessage", new { id = Model.Message.Id }, new { @class = "btn btn-success" })
</div>