MVCForum.Website/ViewModels/SearchViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using MVCForum.Domain.DomainModel;

namespace MVCForum.Website.ViewModels
{
    public class SearchViewModel
    {
        public PagedList<Topic> Topics { get; set; }
        public Dictionary<Category, PermissionSet> AllPermissionSets { get; set; }

        public int? PageIndex { get; set; }
        public int? TotalCount { get; set; }
    }
}

MVCForum.Website/Controllers/MembersController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Text;
using System.Web.Mvc;
using System.Web.Security;
using Facebook;
using MVCForum.Domain.Constants;
using MVCForum.Domain.DomainModel;
using MVCForum.Domain.Interfaces.Services;
using MVCForum.Domain.Interfaces.UnitOfWork;
using MVCForum.Utilities;
using MVCForum.Website.Areas.Admin.ViewModels;
using MVCForum.Website.ViewModels;
using MembershipCreateStatus = MVCForum.Domain.DomainModel.MembershipCreateStatus;
using MembershipUser = MVCForum.Domain.DomainModel.MembershipUser;

namespace MVCForum.Website.Controllers
{
    public class MembersController : BaseController
    {
        private readonly IPostService _postService;
        private readonly IReportService _reportService;
        private readonly IEmailService _emailService;
        private readonly IPrivateMessageService _privateMessageService;

        public MembersController(ILoggingService loggingService, IUnitOfWorkManager unitOfWorkManager, IMembershipService membershipService, ILocalizationService localizationService,
            IRoleService roleService, ISettingsService settingsService, IPostService postService, IReportService reportService, IEmailService emailService, IPrivateMessageService privateMessageService)
            : base(loggingService, unitOfWorkManager, membershipService, localizationService, roleService, settingsService)
        {
            _postService = postService;
            _reportService = reportService;
            _emailService = emailService;
            _privateMessageService = privateMessageService;
        }

        public ActionResult GetByName(string slug)
        {
            using (UnitOfWorkManager.NewUnitOfWork())
            {
                var member = MembershipService.GetUserBySlug(slug);
                var loggedonId = LoggedOnUser != null ? LoggedOnUser.Id : Guid.Empty;
                return View(new ViewMemberViewModel { User = member, LoggedOnUserId = loggedonId });
            }
        }

        /// <summary>
        /// Add a new user
        /// </summary>
        /// <returns></returns>
        public ActionResult Register()
        {
            using (UnitOfWorkManager.NewUnitOfWork())
            {
                var user = MembershipService.CreateEmptyUser();

                // Populate empty viewmodel
                var viewModel = new MemberAddViewModel
                                    {
                                        UserName = user.UserName,
                                        Email = user.Email,
                                        Password = user.Password,
                                        IsApproved = user.IsApproved,
                                        Comment = user.Comment,
                                        AllRoles = RoleService.AllRoles()
                                    };

                // See if a return url is present or not and add it
                var returnUrl = Request["ReturnUrl"];
                if (!string.IsNullOrEmpty(returnUrl))
                {
                    viewModel.ReturnUrl = returnUrl;
                }

                return View(viewModel);
            }
        }

        //
        // POST /Account/Add
        [HttpPost]
        public ActionResult Register(MemberAddViewModel userModel)
        {
            using (var unitOfWork = UnitOfWorkManager.NewUnitOfWork())
            {

                // First see if there is a spam question and if so, the answer matches
                if (!string.IsNullOrEmpty(SettingsService.GetSettings().SpamQuestion))
                {
                    // There is a spam question, if answer is wrong return with error
                    if (userModel.SpamAnswer == null || userModel.SpamAnswer.Trim() != SettingsService.GetSettings().SpamAnswer)
                    {
                        // POTENTIAL SPAMMER!
                        ModelState.AddModelError(string.Empty, LocalizationService.GetResourceString("Error.WrongAnswerRegistration"));
                        return View();
                    }
                }

                var userToSave = new MembershipUser
                {
                    UserName = userModel.UserName,
                    Email = userModel.Email,
                    Password = userModel.Password,
                    IsApproved = userModel.IsApproved,
                    Comment = userModel.Comment,
                };

                var homeRedirect = false;

                // Now check settings, see if users need to be manually authorised
                var manuallyAuthoriseMembers = SettingsService.GetSettings().ManuallyAuthoriseNewMembers;
                if (manuallyAuthoriseMembers)
                {
                    userToSave.IsApproved = false;
                }

                var createStatus = MembershipService.CreateUser(userToSave);
                if (createStatus != MembershipCreateStatus.Success)
                {
                    ModelState.AddModelError(string.Empty, MembershipService.ErrorCodeToString(createStatus));
                }
                else
                {
                    if (!manuallyAuthoriseMembers)
                    {
                        // If not manually authorise then log the user in
                        FormsAuthentication.SetAuthCookie(userToSave.UserName, false);
                        TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                        {
                            Message = LocalizationService.GetResourceString("Members.NowRegistered"),
                            MessageType = GenericMessages.success
                        };
                        homeRedirect = true;
                    }
                    else
                    {
                        ViewBag.Message = new GenericMessageViewModel
                        {
                            Message = LocalizationService.GetResourceString("Members.NowRegisteredNeedApproval"),
                            MessageType = GenericMessages.success
                        };
                    }

                    try
                    {
                        unitOfWork.Commit();
                        if (homeRedirect)
                        {
                            if (Url.IsLocalUrl(userModel.ReturnUrl) && userModel.ReturnUrl.Length > 1 && userModel.ReturnUrl.StartsWith("/")
                            && !userModel.ReturnUrl.StartsWith("//") && !userModel.ReturnUrl.StartsWith("/\\"))
                            {
                                return Redirect(userModel.ReturnUrl);
                            }
                            return RedirectToAction("Index", "Home", new { area = string.Empty });
                        }
                    }
                    catch (Exception ex)
                    {
                        unitOfWork.Rollback();
                        LoggingService.Error(ex);
                        ModelState.AddModelError(string.Empty, LocalizationService.GetResourceString("Errors.GenericMessage"));
                    }
                }

                return View();
            }
        }

        public ActionResult LogonFacebook()
        {
            // Build the Return URI form the Request Url
            if (Request.Url != null)
            {
                var redirectUri = new UriBuilder(Request.Url) { Path = Url.Action("FacebookAuth") };

                var client = new FacebookClient();

                // Generate the Facebook OAuth URL
                // Example: https://www.facebook.com/dialog/oauth?
                //                client_id=YOUR_APP_ID
                //               &redirect_uri=YOUR_REDIRECT_URI
                //               &scope=COMMA_SEPARATED_LIST_OF_PERMISSION_NAMES
                //               &state=SOME_ARBITRARY_BUT_UNIQUE_STRING
                var uri = client.GetLoginUrl(new
                    {
                        client_id = ConfigUtils.GetAppSetting("FacebookAppId"),
                        redirect_uri = redirectUri.Uri.AbsoluteUri,
                        scope = "email",
                    });

                return Redirect(uri.ToString());
            }
            return RedirectToAction("LogOn");
        }

        public ActionResult FacebookAuth(string returnUrl)
        {
            var client = new FacebookClient();
            var oauthResult = client.ParseOAuthCallbackUrl(Request.Url);

            // Build the Return URI form the Request Url
            if (Request.Url != null)
            {
                var redirectUri = new UriBuilder(Request.Url) { Path = Url.Action("FacebookAuth") };

                // Exchange the code for an access token
                dynamic result = client.Get("/oauth/access_token", new
                    {
                        client_id = ConfigUtils.GetAppSetting("FacebookAppId"),
                        redirect_uri = redirectUri.Uri.AbsoluteUri,
                        client_secret = ConfigUtils.GetAppSetting("FacebookAppSecret"),
                        code = oauthResult.Code,
                    });

                // Read the auth values
                string accessToken = result.access_token;

                // Get the user's profile information
                dynamic me = client.Get("/me",
                    new
                        {
                            fields = "first_name,last_name,email",
                            access_token = accessToken
                        });

                // Read the Facebook user values ready for use
                long facebookId = Convert.ToInt64(me.id);
                string firstName = me.first_name;
                string lastName = me.last_name;
                string email = me.email;
                DateTime expires = DateTime.UtcNow.AddSeconds(Convert.ToDouble(result.expires));

MVCForum.Website/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCForum.Domain.Constants;
using MVCForum.Domain.DomainModel;
using MVCForum.Domain.Interfaces.Services;
using MVCForum.Domain.Interfaces.UnitOfWork;
using MVCForum.Website.Application;
using MVCForum.Website.ViewModels;

namespace MVCForum.Website.Controllers
{
    public class SearchController : BaseController
    {
        private readonly IPostService _postService;
        private readonly ITopicService _topicsService;
        private readonly ILuceneService _luceneService;

        public SearchController(ILoggingService loggingService, IUnitOfWorkManager unitOfWorkManager, 
            IMembershipService membershipService, ILocalizationService localizationService, 
            IRoleService roleService, ISettingsService settingsService, 
            IPostService postService, ITopicService topicService, ILuceneService luceneService)
            : base(loggingService, unitOfWorkManager, membershipService, localizationService, roleService, settingsService)
        {
            _postService = postService;
            _topicsService = topicService;
            _luceneService = luceneService;
        }

        public ActionResult Index(int? p, string term)
        {
            using (UnitOfWorkManager.NewUnitOfWork())
            {
                // Set the page index
                var pageIndex = p ?? 1;

                // Get lucene to search
                var foundTopicIds = _luceneService.Search(term).Select(x => x.TopicId).ToList();

                //// Get all the topics based on the search value
                //var topics = _topicsService.SearchTopics(pageIndex,
                //                                     SettingsService.GetSettings().TopicsPerPage,
                //                                     AppConstants.ActiveTopicsListSize,
                //                                     term);

                var topics = _topicsService.GetTopicsByCsv(pageIndex,
                                                     SettingsService.GetSettings().TopicsPerPage,
                                                     AppConstants.ActiveTopicsListSize,
                                                     foundTopicIds);

                // Get all the categories for this topic collection
                var categories = topics.Select(x => x.Category).Distinct();

                // create the view model
                var viewModel = new SearchViewModel
                {
                    Topics = topics,
                    AllPermissionSets = new Dictionary<Category, PermissionSet>(),
                    PageIndex = pageIndex,
                    TotalCount = topics.TotalCount
                };

                // loop through the categories and get the permissions
                foreach (var category in categories)
                {
                    var permissionSet = RoleService.GetPermissions(category, UsersRole);
                    viewModel.AllPermissionSets.Add(category, permissionSet);
                }

                return View(viewModel);
            }
        }

        //public ActionResult Testing(string term)
        //{
        //    var results = _luceneService.Search(term).Select(x => x.TopicId);
        //    return View(results);
        //}

        [ChildActionOnly]
        public PartialViewResult SideSearch()
        {
            return PartialView();
        }

    }

    public static class testing
    {
        public static IEnumerable<TSource> DistinctBy<TSource, TKey>(this IEnumerable<TSource> source, Func<TSource, TKey> keySelector)
        {
            var seenKeys = new HashSet<TKey>();
            foreach (TSource element in source)
            {
                if (seenKeys.Add(keySelector(element)))
                {
                    yield return element;
                }
            }
        }
    }
}

MVCForum.Website/Controllers/TagController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCForum.Domain.Constants;
using MVCForum.Domain.Interfaces.Services;
using MVCForum.Domain.Interfaces.UnitOfWork;
using MVCForum.Website.ViewModels;

namespace MVCForum.Website.Controllers
{
    public class TagController : BaseController
    {
        private readonly ITopicTagService _topicTagService;

        public TagController(ILoggingService loggingService, IUnitOfWorkManager unitOfWorkManager, IMembershipService membershipService, ILocalizationService localizationService, IRoleService roleService, ISettingsService settingsService, ITopicTagService topicTagService)
            : base(loggingService, unitOfWorkManager, membershipService, localizationService, roleService, settingsService)
        {
            _topicTagService = topicTagService;
        }

        [ChildActionOnly]
        [OutputCache(Duration = AppConstants.DefaultCacheLengthInSeconds)]
        public PartialViewResult PopularTags()
        {
            using (UnitOfWorkManager.NewUnitOfWork())
            {
                var popularTags = _topicTagService.GetPopularTags(20);
                var viewModel = new PopularTagViewModel { PopularTags = popularTags };
                return PartialView(viewModel);
            }
        }

    }
}

MVCForum.Website/Views/Members/AdminMemberProfileTools.cshtml
@model MVCForum.Website.ViewModels.ViewMemberViewModel
<div class="adminprofiletools">
    
    <p><a href="@Url.Action("Edit", "Account", new { area = "Admin", Id = Model.User.Id }, null)" class="btn">
           @Html.LanguageString("Members.EditMember")</a></p>
</div>

MVCForum.Website/Views/Members/ChangePassword.cshtml
@model MVCForum.Website.ViewModels.ChangePasswordViewModel

@{
    ViewBag.Title = Html.LanguageString("Members.ChangePassword.Title");
}

@section Header
{
    @(
        Bundle.JavaScript()
            .Add("~/Scripts/jquery.validate.min.js")
            .Add("~/Scripts/jquery.validate.unobtrusive.min.js")            
            .MvcRender("~/scripts/cache/validate-combined_#.js")
    )
}

<p>
    @string.Format(Html.LanguageString("Members.ChangePassword.Text"), Membership.MinRequiredPasswordLength)   
</p>

@using (Html.BeginForm("ChangePassword", "Members", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.ValidationSummary(false)
    @Html.AntiForgeryToken()

        <fieldset>
            <legend>@ViewBag.Title</legend>

            <div class="editor-label">
                @Html.LabelFor(m => m.OldPassword)
            </div>
            <div class="editor-field">
                @Html.PasswordFor(m => m.OldPassword)
                @Html.ValidationMessageFor(m => m.OldPassword)
            </div>

            <div class="editor-label">
                @Html.LabelFor(m => m.NewPassword)
            </div>
            <div class="editor-field">
                @Html.PasswordFor(m => m.NewPassword)
                @Html.ValidationMessageFor(m => m.NewPassword)
            </div>

            <div class="editor-label">
                @Html.LabelFor(m => m.ConfirmPassword)
            </div>
            <div class="editor-field">
                @Html.PasswordFor(m => m.ConfirmPassword)
                @Html.ValidationMessageFor(m => m.ConfirmPassword)
            </div>

            <div class="submit-holder">
                <input type="submit" value="@Html.LanguageString("Buttons.ChangePassword")" class="btn btn-large btn-success" />
            </div>
        </fieldset>

}

MVCForum.Website/Views/Members/Edit.cshtml
@model MVCForum.Website.ViewModels.MemberFrontEndEditViewModel

@{
    ViewBag.Title = @Html.LanguageString("Members.EditProfile");
}
@section Header
{
    @(
        Bundle.JavaScript()
            .Add("~/Scripts/jquery.validate.min.js")
            .Add("~/Scripts/jquery.validate.unobtrusive.min.js")            
            .MvcRender("~/scripts/cache/validate-combined_#.js")
     )  
}
@section side
{
    @Html.Action("ListCategorySideMenu", "Category")
    @Html.Action("PopularTags", "Tag")
}

@using (Html.BeginForm("Edit", "Members", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.HiddenFor(x => Model.Id)

    @Html.ValidationSummary(false)
    
    <fieldset>
        <legend>@ViewBag.Title</legend>
        
        <p class="changepasswordtext">
            @Html.Raw(string.Format(Html.LanguageString("Members.ChangePassword.Link"), string.Format("<a href=\"{0}\">{1}</a>", Url.Action("ChangePassword"), Html.LanguageString("Members.ChangePassword.Title"))))
        </p>

        <div class="editor-label">
            @Html.LabelFor(x => x.UserName)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(x => x.UserName)
            @Html.ValidationMessageFor(x => x.UserName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(x => x.Email)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(x => x.Email)
            @Html.ValidationMessageFor(x => x.Email)
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(x => x.Age)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(x => x.Age)
            @Html.ValidationMessageFor(x => x.Age)
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(x => x.Location)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(x => x.Location)
            @Html.ValidationMessageFor(x => x.Location)
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(x => x.Website)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(x => x.Website)
            @Html.ValidationMessageFor(x => x.Website)
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(x => x.Twitter)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(x => x.Twitter)
            @Html.ValidationMessageFor(x => x.Twitter)
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(x => x.Facebook)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(x => x.Facebook)
            @Html.ValidationMessageFor(x => x.Facebook)
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(x => x.Signature)
        </div>
        <div class="editor-field">
            @Html.EditorFor(x => x.Signature)
            @Html.ValidationMessageFor(x => x.Signature)
        </div>
        
        <div class="submit-holder">
            <input type="submit" class="btn btn-large btn-success" value="@Html.LanguageString("Buttons.Save")" />
        </div>
    </fieldset>
}

MVCForum.Website/Views/Members/ForgotPassword.cshtml
@model MVCForum.Website.ViewModels.ForgotPasswordViewModel

@{
    ViewBag.Title = Html.LanguageString("Members.ForgotPassword.Title");
}

@section Header
{
    @(
        Bundle.JavaScript()
            .Add("~/Scripts/jquery.validate.min.js")
            .Add("~/Scripts/jquery.validate.unobtrusive.min.js")            
            .MvcRender("~/scripts/cache/validate-combined_#.js")
    )
}

@using (Html.BeginForm("ForgotPassword", "Members", FormMethod.Post, new { @class = "form-horizontal" }))
{
    
    @Html.ValidationSummary(false)
    @Html.AntiForgeryToken()

    <fieldset>
        <legend>@ViewBag.Title</legend>

        <div class="editor-label">
            @Html.LabelFor(m => m.EmailAddress)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(m => m.EmailAddress)
            @Html.ValidationMessageFor(m => m.EmailAddress)
        </div>

        <div class="submit-holder">
            <input type="submit" value="@Html.LanguageString("Buttons.ResetPassword")" class="btn btn-large btn-success" />
        </div>
    </fieldset>
    
}

MVCForum.Website/Views/Members/GetByName.cshtml
@using MVCForum.Domain.Constants
@using MVCForum.Utilities
@model MVCForum.Website.ViewModels.ViewMemberViewModel
@{
    ViewBag.Title = string.Concat(Model.User.UserName, Html.LanguageString("Members.ProfileTitle"));
}

@section Header
{
    <script type="text/javascript">
        $(function () {
            $.post(app_base + "Members/GetMemberDiscussions",
                { "Id": '@Model.User.Id' },
                function (data) {
                    $(".memberdiscussions").html(data);
                });
                TimeBadges();
        });        
        function TimeBadges() {                    
            var timeBadgeViewModel = new Object();
            timeBadgeViewModel.Id = '@Model.User.Id';
            var strung = JSON.stringify(timeBadgeViewModel);
            $.ajax({
                url: app_base + 'Badge/Time', type: 'POST', dataType: 'json', data: strung,
                contentType: 'application/json; charset=utf-8',
                success: function (data) {

                },
                error: function (xhr, ajaxOptions, thrownError) {
                    ShowUserMessage("Error: " + xhr.status + " " + thrownError);
                }
            });            
        }        
    </script>
}

@section side
{
    @Html.Action("ListCategorySideMenu", "Category")
}

<div class="memberprofilepublic">    
    
<h2>@Model.User.UserName</h2>

    <div class="row">
        
        <div class="span2 memberavatardetails">
            <p><img src="@StringUtils.GetGravatarImage(Model.User.Email, AppConstants.GravatarProfileSize)" alt="@Model.User.UserName"></p>
            <p>@Html.LanguageString("Members.Profile.Joined") @Model.User.CreateDate.ToShortDateString()</p>
            <p>@Html.LanguageString("Members.Profile.Posts") @Model.User.Posts.Count</p>
            <p>@Html.LanguageString("Members.Profile.Points") @Model.User.TotalPoints</p>
            
            @if (User.IsInRole(AppConstants.AdminRoleName))
            {
              if (Convert.ToBoolean(Model.User.IsExternalAccount))
              {
                <p>@Html.LanguageString("Members.Profile.IsSocialAccount")</p>    
              }
            }
            
            @if(User.Identity.IsAuthenticated && Html.Settings().EnableMemberReporting && Model.User.Id != Model.LoggedOnUserId)
            {
                <p><a href="@Url.Action("Report", "Members", new { id = Model.User.Id }, null)" class="btn">@Html.LanguageString("Buttons.Report")</a></p>
            }
            
            @if (User.IsInRole(AppConstants.AdminRoleName))
            {
                <div class="memberprofileadminsection">
                    @Html.Partial("AdminMemberProfileTools")
                </div>
            }
        </div>
    
        <div class="span7 membermaindetails">
            
            <div class="row">                
                <div class="span3 memberbio">
                    
                    <p>@Html.LanguageString("Members.Profile.Age") @Html.Raw(Model.User.Age > 0 ? Model.User.Age.ToString() : "")</p>
                    <p>@Html.LanguageString("Members.Profile.Location") @Html.Raw(string.IsNullOrEmpty(Model.User.Location) ? "" : Model.User.Location)</p>
                    <p>@Html.LanguageString("Members.Profile.Website") @Html.Raw(string.IsNullOrEmpty(Model.User.Website) ? "" : string.Format("<a href='{0}' rel='nofollow'>{0}</a>", Model.User.Website))</p>
                    <p>@Html.LanguageString("Members.Profile.Twitter") @Html.Raw(string.IsNullOrEmpty(Model.User.Twitter) ? "" : string.Format("<a href='{0}' rel='nofollow'>{0}</a>", Model.User.Twitter))</p>
                    <p>@Html.LanguageString("Members.Profile.Facebook") @Html.Raw(string.IsNullOrEmpty(Model.User.Facebook) ? "" : string.Format("<a href='{0}' rel='nofollow'>{0}</a>", Model.User.Facebook))</p>
                </div>

                <div class="span4 memberlatesttopics">
                    <h3>@Html.LanguageString("Members.Profile.DiscussionActivity")</h3>
                    <div class="memberdiscussions">
                        <span class="ajaxspinner" title="@Html.LanguageString("Ajax.PleaseWait")">@Html.LanguageString("Ajax.PleaseWait")</span>
                    </div>
                </div>
            </div>
            
            <div class="row">
                <div class="span7 badgeactivity">
                    <h3>@Html.LanguageString("Members.Profile.Badges")</h3>
                    <div class="memberactivity">
                            @if (Model.User.Badges != null && Model.User.Badges.Any())
                            {
                                <ul class="memberbadgelist">
                                @foreach (var badge in Model.User.Badges)
                                {
                                    <li>
                                        <img src="@Url.Content(AppHelpers.ReturnBadgeUrl(badge.Image))" alt="@badge.Name" title="@badge.Name"/>  @Html.Raw(badge.DisplayName)
                                    </li>
                                }
                                </ul>
                            }
                    </div>
                </div>
            </div>

        </div>

    </div>

</div>

MVCForum.Website/Views/Members/LatestMembersJoined.cshtml
@model MVCForum.Website.ViewModels.ListLatestMembersViewModel

@if(Model.Users.Any())
{
    <ul class="latestmembersjoined">
    @foreach (var user in Model.Users)
    {
        <li><a href="@Html.Raw(user.Value)">@Html.Raw(user.Key)</a></li>
    }
    </ul>
}

MVCForum.Website/Views/Members/LogOn.cshtml
@using MVCForum.Utilities
@model MVCForum.Website.ViewModels.LogOnViewModel
@{
    ViewBag.Title = Html.LanguageString("LogOn.LogOn");
}

@section Header
{
    @(
        Bundle.JavaScript()
        .Add("~/Scripts/jquery.validate.min.js")
        .Add("~/Scripts/jquery.validate.unobtrusive.min.js")
        .MvcRender("~/scripts/cache/validate-combined_#.js")
    )
}

<div class="row">


    <div class="span4 mainlogonform">

        @Html.ValidationSummary(false)

        <h3>@ViewBag.Title</h3>

        @using (Html.BeginForm("LogOn", "Members", FormMethod.Post, new { @class = "form-horizontal" }))
        {            
            <p>@Html.Raw(string.Format(Html.LanguageString("Members.LogOnMessage"), Html.ActionLink("Register", "Register")))</p>

            <div class="editor-label">
                @Html.LabelFor(m => m.UserName)
            </div>
            <div class="editor-field">
                @Html.TextBoxFor(m => m.UserName)
                @Html.ValidationMessageFor(m => m.UserName)
            </div>

            <div class="editor-label">
                @Html.LabelFor(m => m.Password)
            </div>
            <div class="editor-field">
                @Html.PasswordFor(m => m.Password)
                @Html.ValidationMessageFor(m => m.Password)
            </div>

            <div class="editor-label">
                <label class="checkbox inline">
                    @Html.CheckBoxFor(m => m.RememberMe)
                    @Html.LabelFor(m => m.RememberMe)
                </label>
            </div>

            <div class="submit-holder">
                <input type="submit" class="btn btn-success btn-large" value="@Html.LanguageString("Buttons.LogOn ")" />
            </div>

            @Html.HiddenFor(x => x.ReturnUrl)
        }
        <p class="forgotpasswordtext"><a href="@Url.Action("ForgotPassword")">@Html.LanguageString("Members.ForgotPassword.Link")</a></p>
    </div>
    
    @if(Html.Settings().EnableSocialLogins == true)
    {
        <div class="span1 loginortext">
            @Html.LanguageString("Members.LoginOrText")
        </div>

        <div class="span4 oauthbuttons">
            
            @if (!string.IsNullOrEmpty(ConfigUtils.GetAppSetting("FacebookAppId")) && !string.IsNullOrEmpty(ConfigUtils.GetAppSetting("FacebookAppSecret")))
            {
                <div class="facebookloginbutton">
                    @Html.ActionLink(Html.LanguageString("Members.LogonFacebookButton"), "LogonFacebook", "Members", null, new { @class = "facebookloginbutton" })
                </div>   
            }
            else
            {
                @Html.LanguageString("Facebook.Error.EnabledButNotAddedKeys")
            }

        </div>
    }


</div>

MVCForum.Website/Views/Members/SideAdminPanel.cshtml
@model MVCForum.Website.ViewModels.ViewAdminSidePanelViewModel
           
<div class="side-box profile-box">
    <h5>@Html.LanguageString("SideBox.MyTools")</h5>

    <ul>
        <li>@Html.ActionLink(Model.CurrentUser.UserName, "Edit", "Members", new { id = Model.CurrentUser.Id }, null)</li>

        @if(Html.Settings().EnablePrivateMessages)
        {
            var count = Model.NewPrivateMessageCount <= 0 ? null : string.Format("({0})", Model.NewPrivateMessageCount);
            <li><a href="@Url.Action("Index", "PrivateMessage")">@Html.LanguageString("PM.PrivateMessages") @count</a></li>
        }

        <li>@Html.ActionLink(Html.LanguageString("Members.SearchMembers"), "Search", "Members")</li>
        <li>@Html.ActionLink(Html.LanguageString("LogOn.LogOff"), "LogOff", "Members")</li>
    </ul>
</div>